  GNU nano 6.2                   Dockerfile.yaml                            
FROM node:16

WORKDIR /app

COPY client/package.json client/package-lock.json ./client/
COPY server/package.json server/package-lock.json ./server/

# Install dependencies for the client
RUN cd client && npm install

# Install dependencies for the server
RUN cd server && npm install

# Copy the app code
COPY client ./client
COPY server ./server


EXPOSE 3000

EXPOSE 1335

CMD cd server && npm start